name: ci
on: [push, pull_request]

jobs:
  secretlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: yarn install
        run: yarn install
      - name: run secretlint
        run: yarn secretlint
